kube-vip/kube-vip-cloud-provider

Makefile, pkg/ipam/ipam_test.go
- add test action to Makefile
- fixup test runs by using testify package to ignore test element order
Signed-off-by: Steve Sloka <slokas@vmware.com>
=> Add test action to Makefile

pkg/provider/loadBalancer.go
I was hitting this when running `make build` on main:
```
...
pkg/provider/provider.go:83:22: not enough arguments in call to newLoadBalancer
have (*kubernetes.Clientset, string, string)
want (*kubernetes.Clientset, string, string, string)
make: *** [Makefile:28: kube-vip-cloud-provider] Error 2
```
`serviceCidr` isn't used in this function so I removed it so `make build` can successfully complete again.
=> Remove extra arg in newLoadBalancer

pkg/ipam/ipam.go, pkg/provider/loadBalancer.go
When there is a range that crosses the third octet, there are 2 IPs that shouldn't be used: the ones that end in 255 or 0.
There is also a test that catch this situation and that fails; this PR pass it: "single range, across third octet" in `ipam_test.go`.
=> Exlude invalid IPs when range crosses the third octet

pkg/provider/loadBalancer.go, pkg/provider/loadBalancer_test.go
`LoadBalancer` would poll existing IPs only for a specific namespace. Modified logic to determine if user is using a global cidr or range first. If global it collects all services in all namespaces into `existingServiceIPS` and determines what is used from there.
=> fix ip allocation across namespaces

README.md, pkg/ipam/addressbuilder.go, pkg/provider/loadBalancer.go, pkg/provider/loadBalancer_test.go
This pull request adds the logic to handle the special DHCP workflow with `0.0.0.0` by setting the CIDR to `0.0.0.0/32`. It will give all _LoadBalancers_ the same IP.
=> Embed logic for DHCP workflow

README.md, manifest/kube-vip-cloud-controller.yaml
Change kvcp from statefulset to deployment
Fix #https://github.com/kube-vip/kube-vip-cloud-provider/issues/45
* Change readme
* Add upgrade strategy to deployment
* Add tolerations and affinity rules to allow deploying kube-vip-cloud-provider on control plane
=> Change kvcp from statefulset to deployment

go.mod, go.sum
CVE-2022-27664 | high | 7.5 | golang.org/x/net
-- | -- | -- | --
=> Fix CVE of golang.org/x/net

README.md, pkg/provider/loadBalancer.go, pkg/provider/loadBalancer_test.go, pkg/provider/provider.go
Fix # https://github.com/kube-vip/kube-vip-cloud-provider/issues/51
* Add new annotation `kube-vip.io/loadbalancerIPs` to specify the loadbalancer ip for service. Use plural in case we need to support dual stack in the future. For backward compatibility, add the annotation if `service.spec.loadbalancerIP` is presented while annotation is missing.
* At this moment, still add `service.spec.loadbalancerIP`
* Remove label `ip-address` in case of ipv6 case. Since `:` is not supported
* Update related doc
* Unit test
=> Deprecate loadbalancerIP. Pin service IP using annotations

Makefile, pkg/provider/loadBalancer.go, pkg/provider/loadBalancer_test.go
In PR https://github.com/kube-vip/kube-vip-cloud-provider/pull/52, we deprecated loadbalancerIP and old label.
This one is to fix the label name.
Also update default image tag in MakeFile
=> Fix name of legacy label, update image tag

README.md, go.mod, go.sum, pkg/ipam/addressbuilder.go, pkg/ipam/ipam.go, pkg/ipam/ipam_test.go, pkg/provider/loadBalancer.go, pkg/provider/loadBalancer_test.go
* Add IPV6 ipam function
* Refactor ipam logic using library go4.org/netipx. Previously the logic to check each ip in the range is not suitable for ipv6 address since there are so many.
* Now of ipv4 address, only skip `.0` and `.255`. Doesn't skip ipv6 address
* More unit test
=> IPV6 support

pkg/provider/loadBalancer.go, pkg/provider/loadBalancer_test.go
If customer only sets annotation `kube-vip.io/loadbalancerIPs`, don't allocate new ip, don't set spec.loadbalancerIP, only add label `implementation` if necessary
Fix https://github.com/kube-vip/kube-vip-cloud-provider/issues/59
=> Fix the logic of sync service.

README.md, pkg/ipam/addressbuilder.go, pkg/ipam/ipam.go, pkg/ipam/ipam_test.go, pkg/provider/loadBalancer.go, pkg/provider/loadBalancer_test.go
As a follow-on to https://github.com/kube-vip/kube-vip/pull/687, I've decided to implement handling for dualstack loadbalancer services in kube-vip-cloud-provider by making the following changes:
- `kube-vip.io/loadbalancerIPs` may now contain multiple comma-separated IP addresses. This may be a breaking change without the PR from above
- Pools or ranges in the ConfigMap may now contain mixed IP families and they will be properly partitioned into a IPv4 bucket and an IPv6 bucket internally.
- kube-vip-cloud-provider now pays special attention to the ipFamilyPolicy field on the Service to determine if dualstack is preferred or required and assigns IPs according to the order specified in the ipFamilies field.
Any comments or concerns welcome!
=> Support for dualstack loadbalancer services

Dockerfile, Makefile
Fix https://github.com/kube-vip/kube-vip-cloud-provider/issues/89
-X k8s.io/component-base/version.gitVersion=$(VERSION)  in go build so it could set version in log
Now example
```
I0119 23:29:26.520559       1 controllermanager.go:145] Version: v0.0.7
```
=> Update version to 0.0.9, and add arg to set version during build

.github/workflows/release.yml, Dockerfile
Fix https://github.com/kube-vip/kube-vip-cloud-provider/issues/95
Now the build job is missing VERSION variable. Causing the image built by release job panic when running.
```
panic: version string "" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)" 
```
Now with the fix, the release job adds the version https://github.com/kube-vip/kube-vip-cloud-provider/actions/runs/7615359814/job/20739705540
```
#37 [linux/amd64 builder 5/5] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.local/share/golang     CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w -extldflags -static -X k8s.io/component-base/version.gitVersion=v0.0.9-alpha" -o kube-vip-cloud-provider
```
And the dev image …
=> Add VERSION variable to publish and release job

Makefile, test/e2e/defaultconfig/default_config_test.go, test/e2e/deployment.go, test/e2e/framework.go
Now in e2e test, when deploying kube-vip-cloud-provider, by default it only use image inside manifest.yaml, it should be updated to whatever is generated in the e2e test.
Also the imagepullpolicy should be pullIfNotPresent
Also group the testsuite by kube-vip-cloud-provider configuration.
=> Update the deployment's default image

pkg/ipam/ipam.go
Fix https://github.com/kube-vip/kube-vip-cloud-provider/issues/114
=> Use go mod 1.22 way of range over integer syntax

.github/workflows/trivy-scan.yml
Fix https://github.com/kube-vip/kube-vip-cloud-provider/issues/134
It was failing because of wrong version tag
=> Fix the version in trivy scan

Makefile, pkg/ipam/ipam.go
The recent actions of the "Build and Test" workflow did not execute the unittests anymore.
Output was only "(make: 'test' is up to date.)"
This commit adds "test" as phony target in make.
Solved a Bug in FindFreeAddress() introduced with 7b00941f6efb55edaacbc7d1c4befb63861aa75c
=> makefile: ensure that test-target is executed always

README.md, pkg/provider/loadBalancer.go, pkg/provider/loadBalancer_test.go, pkg/provider/provider.go, test/e2e/common.go
Kube-vip 0.8.0 supports `kube-vip.io/serviceInterface` annotation on service type LB. Now user can specify a ip range/cidr at namespace level, we would assume these ips within a namespace should share the same interface, then we support specifying interface per namespace level by
Fix https://github.com/kube-vip/kube-vip-cloud-provider/issues/144
=> Support specifying service interface per namespace or at global level

.gitignore, README.md, pkg/provider/loadBalancer.go, pkg/provider/loadbalancerclass.go, pkg/provider/loadbalancerclass_test.go, pkg/provider/provider.go, test/e2e/custom_loadbalancerclass/custom_loadbalancerclass_test.go, test/e2e/loadbalancerclass/loadbalancerclass_test.go
When the KUBEVIP_ENABLE_LOADBALANCERCLASS environment variable is enabled kube-vip-cloud-provider will only allocate ip to service with `spec.loadBalancerClass: kube-vip.io/kube-vip-class`
The KUBEVIP_CUSTOM_LOADBALANCERCLASS_NAME environment variable has been added to provide an option to override the default class name `kube-vip.io/kube-vip-class` to any other value.
=> Added custom loadbalancerclass name option

.github/workflows/generate-release-note.yml, match-release-tag.sh
1. Checks whether new tag is valid or not (vx.x.x)
2. Find the second latest tag and use it as a comparison to generate note
=> Add github action to publish release note automatically
